USE Club_Management_System;


CREATE TABLE STUDENT (

	StudentID INTEGER PRIMARY KEY,
	StudentName NVARCHAR(60) NOT NULL,
	ContactNo VARCHAR(8) NOT NULL,
	EmailAddress VARCHAR(50) NOT NULL UNIQUE
	
);



CREATE TABLE CLUB(

	ClubID INTEGER PRIMARY KEY,
	ClubName NVARCHAR(60) NOT NULL UNIQUE,
	ClubDetails VARCHAR(1000) NOT NULL,
	Location VARCHAR(50) NOT NULL,
	PresidentID INTEGER NOT NULL UNIQUE,
	FOREIGN KEY (PresidentID) REFERENCES STUDENT (StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
	

);

CREATE TABLE CLUB_REGISTRATION(
	
	RegistrationID INTEGER PRIMARY KEY,
	StudentID INTEGER NOT NULL,
	FOREIGN KEY (StudentID) REFERENCES STUDENT (StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
	ClubID INTEGER NOT NULL,
	FOREIGN KEY (ClubID) REFERENCES CLUB (ClubID),
	Status NVARCHAR(10) NOT NULL

);




INSERT INTO STUDENT(StudentID, StudentName, ContactNo, EmailAddress) VALUES (2116860, 'Wayne Darween', 59118706, 'wayne@gmail.com')

INSERT INTO CLUB_REGISTRATION(RegistrationID, StudentID, ClubID, Status) VALUES (3, 2116860, 2, 'pending')

INSERT INTO CLUB(ClubID, ClubName, ClubDetails, Location, PresidentID) VALUES (2, 'Science For Fun', 'Fun Scientific Experiments', 'S01', 2116860)



SELECT * FROM CLUB;
SELECT * FROM STUDENT;
SELECT * FROM CLUB_REGISTRATION;


